services:
  - type: web
    name: jc-ticket-be
    env: node
    region: singapore
    plan: free
    rootDir: be
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        value: https://jc-ticket.vercel.app
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GMAIL_EMAIL
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: EMAIL_FROM
        value: JC-Ticket <120304thuan@gmail.com>
      - key: EMAIL_SERVICE
        value: gmail
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: PAYOS_CLIENT_ID
        sync: false
      - key: PAYOS_API_KEY
        sync: false
      - key: PAYOS_CHECKSUM_KEY
        sync: false
      - key: VNP_TMNCODE
        sync: false
      - key: VNP_HASHSECRET
        sync: false
      - key: VNP_URL
        value: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      - key: VNP_RETURNURL
        value: https://jc-ticket.onrender.com/api/payment/vnpay/return
      - key: VNP_IPNURL
        value: https://jc-ticket.onrender.com/api/payment/vnpay/ipn
      - key: ZALOPAY_APP_ID
        value: "2554"
      - key: ZALOPAY_KEY1
        sync: false
      - key: ZALOPAY_KEY2
        sync: false
      - key: ZALOPAY_ENDPOINT
        value: https://sb-openapi.zalopay.vn/v2
      - key: ZALOPAY_CALLBACK_URL
        value: https://jc-ticket.onrender.com/api/payment/zalopay/callback
